
version: "3.4"

services:
  client:
    stdin_open: true 
    build: 
      context: ./
      dockerfile: DockerFile
    environment:
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    command: npm start
    